jdk: 
  - oraclejdk7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java7-installer
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
before_script:
  - ./gradlew --version
script: ./gradlew --no-daemon -s -PbuildInfo.build.number=$TRAVIS_BUILD_NUMBER -PbuildInfo.buildUrl=https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_JOB_ID}
  -PbuildInfo.buildAgent.name=$USER -PbuildInfo.principal=$USER -Dscan clean jar
